#example 1: try - except - finally block
try:
	x = 5
	y = 0

	z = x/y
except:
	print("Error!")
finally:
	print("All done!")
